// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout/internal/biz"
	"github.com/go-kratos/kratos-layout/internal/conf"
	"github.com/go-kratos/kratos-layout/internal/data"
	"github.com/go-kratos/kratos-layout/internal/server"
	"github.com/go-kratos/kratos-layout/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(db, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repo := data.NewRepo(dataData, logger)
	bizService := biz.NewService(repo, logger)
	serviceService, cleanup3, err := service.NewService(bizService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(confServer, serviceService)
	app := newApp(logger, httpServer, bizService)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
